[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'fatih/vim-go'

#[[plugins]]
#repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'vim-scripts/rdark'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'vim-scripts/twilight'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'osyo-manga/vim-monster'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'yuku-t/vim-ref-ri'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'nightsense/carbonized'

[[plugins]]
repo = 'Zabanaa/neuromancer.vim'

[[plugins]]
repo = 'hzchirs/vim-material'

[[plugins]]
repo = 'vim-scripts/mayansmoke'

[[plugins]]
repo = 'bluz71/vim-moonfly-colors'

[[plugins]]
repo = 'cnj4/horseradish256'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'KabbAmine/gulp-vim'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'ujihisa/unite-font'

[[plugins]]
repo = 'therubymug/vim-pyte'

#[[plugins]]
#repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'osyo-manga/unite-airline_themes'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'vim-scripts/Highlight-UnMatched-Brackets'

[[plugins]]
repo = 'nightsense/simplifysimplify'

[[plugins]]
repo = 'https://gitlab.com/zerogoichi/Fazima.git'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'

[[plugins]]
repo = 'vim-jp/vim-java'

#[[plugins]]
#repo = 'thinca/vim-quickrun'

#[[plugins]]
#repo = 'mikelue/vim-maven-plugin'

#[[plugins]]
#repo = 'hackhowtofaq/vim-solargraph'

# TypeScript
[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'Shougo/NeoSnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tmsanrinsha/SyntaxRange'
