mklink %USERPROFILE%\.bash_profile %~dp0\.bash_profile
mklink %USERPROFILE%\.bashrc %~dp0\.bashrc
mklink %USERPROFILE%\.gitconfig %~dp0\.gitconfig
mklink %USERPROFILE%\.gvimrc %~dp0\.gvimrc
mklink %USERPROFILE%\.vimrc %~dp0\.vimrc
mklink %USERPROFILE%\.vrapperrc %~dp0\.vrapperrc
mklink %USERPROFILE%\_vsvimrc %~dp0\_vsvimrc
mklink %USERPROFILE%\.vim\rc\dein.toml %~dp0\dein.toml
mklink %USERPROFILE%\.vim\rc\dein_lazy.toml %~dp0\dein_lazy.toml
mklink %USERPROFILE%\.vim\ginit.vim %~dp0\ginit.vim
